# Define AWS account profiles
[string[]]$awsProfiles = @('', '','','') #Replace with the accounts you want to audit.

# Define the local directory for saving results
$localResultsDirectory = ""  # Replace with your desired local directory

# Path to ScoutSuite executable
$scoutExecutable = "ScoutSuite\scout.py"

# Get the current date
$currentDatetime = Get-Date -Format 'yyyy-MM-dd_HH-mm-ss'

# Iterate through each AWS profile and run ScoutSuite
foreach ($profile in $awsProfiles) {
    
    # Create a temporary directory for the current profile and date
    $tempDirectory = Join-Path -Path $localResultsDirectory -ChildPath "$profile\$currentDatetime"
    if (-Not (Test-Path $tempDirectory)) {
        New-Item -Path $tempDirectory -ItemType Directory -Force
    }

    # Run ScoutSuite for the current profile
    Write-Host "Running ScoutSuite for profile: $profile"
    $scoutSuiteCommand = "python $scoutExecutable aws --profile $profile --report-dir $tempDirectory"
    Invoke-Expression $scoutSuiteCommand

    Write-Host "Uploading results to S3 bucket: $s3BucketName"
    
    # Get all report files generated by ScoutSuite in the temp directory
    $reportFiles = Get-ChildItem -Path $tempDirectory -Recurse

    foreach ($file in $reportFiles) {
        #Define the key for S3
        $s3Key = "scoutsuite-reports/$profile/$currentDatetime/$($file.Name)"
        
        Upload each file to S3 (commented out)
        Write-S3Object -BucketName $s3BucketName -File $file.FullName -Key $s3Key -CannedACLName public-read
        Write-Host "Uploaded: $($file.Name) to s3://$s3BucketName/$s3Key"
        
        #Write-Host "Saved report locally: $($file.FullName)"
    }

    Remove-Item -Path $tempDirectory -Recurse -Force
}

Write-Host "ScoutSuite audit completed and results saved locally for all profiles."
